import constants from './constants.js';

const LOAD_ALL_RECIPES = { type: constants.LOAD_ALL_RECIPES };
const ADD_RECIPE_INPUT = { type: constants.ADD_RECIPE_INPUT };
const QUERY_INPUT = { type: constants.QUERY_INPUT };
const SORT_BY_CATEGORY = { type: constants.SORT_BY_CATEGORY};
const
FILTER_RECIPES = { type: constants.FILTER_RECIPES };
const SHOW_HIDE_DROPDOWN = { type: constants.SHOW_HIDE_DROPDOWN};
const CURRENT_RECIPE = { type: constants.CURRENT_RECIPE };
const EDIT_RECIPE_INPUT = { type: constants.EDIT_RECIPE_INPUT };
const REMOVE_FILTERED_RECIPES = { type: constants.REMOVE_FILTERED_RECIPES };

const actions = {
  LOAD_ALL_RECIPES: LOAD_ALL_RECIPES,
  ADD_RECIPE_INPUT: ADD_RECIPE_INPUT,
  QUERY_INPUT: QUERY_INPUT,
  SORT_BY_CATEGORY: SORT_BY_CATEGORY,
  FILTER_RECIPES: FILTER_RECIPES,
  SHOW_HIDE_DROPDOWN: SHOW_HIDE_DROPDOWN,
  CURRENT_RECIPE: CURRENT_RECIPE,
  EDIT_RECIPE_INPUT: EDIT_RECIPE_INPUT,
  REMOVE_FILTERED_RECIPES: REMOVE_FILTERED_RECIPES
};

module.exports = actions;
