module.exports = {
  //loading recipes
  LOAD_ALL_RECIPES: 'LOAD_ALL_RECIPES',
  SORT_BY_CATEGORY: 'SORT_BY_CATEGORY',
  FILTER_RECIPES: 'FILTER_RECIPES',
  //filtering recipes
  QUERY_INPUT: 'QUERY_INPUT',
  REMOVE_FILTERED_RECIPES: 'REMOVE_FILTERED_RECIPES',
  //adding and editing recipes
  CURRENT_RECIPE: 'CURRENT_RECIPE',
  ONCHANGE_RECIPE_INPUT: 'ONCHANGE_RECIPE_INPUT',
  SET_EDIT_RECIPE_INPUT: 'SET_EDIT_RECIPE_INPUT',
  CLEAR_RECIPE_INPUT: 'CLEAR_RECIPE_INPUT',
  //styling
  SHOW_HIDE_DROPDOWN: 'SHOW_HIDE_DROPDOWN'
};
