module.exports = {
  LOAD_ALL_RECIPES: 'LOAD_ALL_RECIPES',
  ADD_RECIPE_INPUT: 'ADD_RECIPE_INPUT',
  QUERY_INPUT: 'QUERY_INPUT',
  FILTER_RECIPES: 'FILTER_RECIPES',
  SHOW_HIDE_DROPDOWN: 'SHOW_HIDE_DROPDOWN'
};
